name: Merge to Main branch

on:
  push:
    branches:
    - main

env:
  TERRAFORM_VERSION: "1.2.9"

jobs:
  merge-main-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3.1.1

      - name: Terraform Init
        id: init
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: terraform init
      
      - name: Terraform Apply
        id: apply
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: terraform apply -auto-approve